### ISSUE TITLE
Support Multiple Workers

### ISSUE THREAD

**Issue by DaemonDude23** [logzio/fluentd-plugin-logzio#22]
Support [multiple workers](https://docs.fluentd.org/v1.0/articles/performance-tuning-single-process#multi-workers):

With this part of the configuration defined:

```
<system>
  workers 4
</system>
```

`fluentd` fails to start:

> Plugin 'logzio_buffered' does not support multi workers configuration (Fluent::LogzioOutputBuffered)

```
2018-09-21 20:45:19 +0000 [info]: fluent/log.rb:322:info: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2018-09-21 20:45:19 +0000 [error]: fluent/log.rb:362:error: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Plugin 'logzio_buffered' does not support multi workers configuration (Fluent::LogzioOutputBuffered)"
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin.rb:178:in `configure'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:130:in `add_match'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:72:in `block in configure'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:64:in `each'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:64:in `configure'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:112:in `configure'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/engine.rb:131:in `configure'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/engine.rb:96:in `run_configure'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:795:in `run_configure'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:579:in `dry_run'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:597:in `supervise'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:502:in `run_supervisor'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/bin/fluentd:8:in `<top (required)>'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2018-09-21 20:45:19 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
```

**Comment by idohalevi** [comment]
@chicken231 
I'll add it to our todo list. I hope to solve it quickly if you want to save time and have a solution feel free to send a PR

**Comment by DaemonDude23** [comment]
Thanks.
It's not a show-stopper for me at the moment as I'm using the more hacky [multiprocess input plugin](https://docs.fluentd.org/v0.12/articles/in_multiprocess) for my aggregators, but native support for it in v1.0 would be good to have.

If I knew Ruby, I'd give it a shot.

**Comment by idohalevi** [comment]
@chicken231 
Do you think you can check if https://github.com/logzio/fluent-plugin-logzio/pull/24 works for you?

**Comment by DaemonDude23** [comment]
@idohalevi 
I compiled the plugin from your fork and tested it. It's working fine. Thank you.

**Comment by idohalevi** [comment]
@chicken231 
Great, I will do some additional checking during the week and merge
