### ISSUE TITLE
Error after updating to fluentd 1.x

### ISSUE THREAD

**Issue by fields** [logzio/fluentd-plugin-logzio#35]
I am upgrading from td-agent 2 to td-agent 3 (fluentd 1.x), and I'm getting this error on startup:

```
2020-09-16 19:31:19 +0000 [error]: #0 unexpected error error_class=ArgumentError error="wrong number of arguments (given 2, expected 0)"
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:530:in `initialize'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-logzio-0.0.20/lib/fluent/plugin/out_logzio_buffered.rb:47:in `new'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-logzio-0.0.20/lib/fluent/plugin/out_logzio_buffered.rb:47:in `start'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:200:in `block in start'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:188:in `each'
2020-09-16 19:31:19 +0000 [debug]: #0 enqueue_thread actually running
2020-09-16 19:31:19 +0000 [debug]: #0 flush_thread actually running
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:188:in `block in lifecycle'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:175:in `each'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:175:in `lifecycle'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:199:in `start'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/engine.rb:248:in `start'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/engine.rb:147:in `run'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/supervisor.rb:603:in `block in run_worker'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/supervisor.rb:840:in `main_process'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/supervisor.rb:594:in `run_worker'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/bin/fluentd:8:in `<top (required)>'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2020-09-16 19:31:19 +0000 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
2020-09-16 19:31:19 +0000 [error]: #0 unexpected error error_class=ArgumentError error="wrong number of arguments (given 2, expected 0)"
```

This appears to be an issue with the logzio plugin, but I'm not sure where to look to troubleshoot this. I've updated the logz.io configuration in td-agent.conf to correspond to the new format:

```
  <store>
  @type logzio_buffered
    endpoint_url https://listener.logz.io:8071?token={{ logzio_token }}&type=fluentd
    output_include_time true
    output_include_tags true
    <buffer>
      @type    file
      path    /var/log/td-agent/buffer/logzio
      flush_interval 10s
      chunk_limit_size 16m 
      queue_limit_length 4096
    </buffer>
  </store>
```

Any ideas about what could be wrong here?

**Comment by ekhaydarov** [comment]
I have this issue as well. it seems its an issue with `net-http-persistent` client upgrade to 3.x.x version. if you pin it to 2.9.x you should be able to run it correctly

However it would be good for maintainers of this library to come and fix this issue so that net-http-persistence could be upgraded

**Comment by tarokkk** [comment]
I think they don't bother fixing this. This issue is open since June https://github.com/logzio/fluent-plugin-logzio/issues/33

**Comment by ekhaydarov** [comment]
@tarokkk the issue on banzaicloud side is also not being adressed though :( https://github.com/banzaicloud/logging-operator/issues/659

**Comment by mirii1994** [comment]
@fields @ekhaydarov 
Hi guys, sorry for the late response!
fluent-plugin-logzio v. 0.0.21 is out and should solve this issue #36 
Let us know if you're having further issues :)

**Comment by ekhaydarov** [comment]
all works thanks

**Comment by mirii1994** [comment]
@ekhaydarov Great! Closing this issue :)
